### ISSUE TITLE
Investigate current (Rel.12?) mobile support (e.g. for Android)

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-mbms-mw#11]
Investigate what needs to be done to support migration to Android. What exactly needs to be implemented and changed to support Android devices. 

This should also include an investigation how native Android implementations provide the 5G broadcast signal to the middleware.

**Comment by dsilhavy** [comment]
An example implementation was provided by @kuehnhammer and @johannmika , the code is available here: https://github.com/5G-MAG/rt-mbms-mw-android

**Comment by fredericgermain** [comment]
Hi!

I cannot access https://github.com/5G-MAG/rt-mbms-mw-android (404).
I guess it's not public.

Is there any plan to make it public? Or it is just a misconfiguration maybe?

**Comment by dsilhavy** [comment]
@fredericgermain You are right, the repo is not public yet. We are still working on making this public and including installation instructions. We will keep you updated once we are ready, I don't have an exact date for this yet.

**Comment by fredericgermain** [comment]
Ok.
Even though most modems are probably not configured properly for mbms, that would be an interesting to see this running on android devices directly.
I'll keep an eye for that that repo then until it's made available :)
