### ISSUE TITLE
Missing package in build

### ISSUE THREAD

**Issue by Simons-CSharp** [5G-MAG/rt-mbms-mw#20]
**Describe the bug**
ninja build process of rt-mbms-mw fails with No package 'gmime-3.0' found

**To Reproduce**
cmake -DCMAKE_INSTALL_PREFIX=/usr -GNinja ..

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu 20.04

**Additional context**

**Comment by Simons-CSharp** [comment]
Sorry this was a copy and paste error-please delete.

**Comment by dsilhavy** [comment]
No problem, closing this then
